apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-s2wp
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0072-tenant/tkrw-pr712-0075-0072-app/devfile-sample-s2wp@sha256:6d2990a2a7a7897e93b3a7fa8da92c654684c410c439336b60862b9dc87c6b32
        name: my-nodejs
        resources: {}
status: {}
